CC = g++
CFALGS = -Wall

OBJ1 = 10.1.o 
OBJ2 = 10.2a.o
OBJ3 = 10.3.o


all: 10.1 10.2a 10.3

10.1: $(OBJ1)
	$(CC) $(CFLAGS) -o 10.1 $(OBJ1)

10.2a: $(OBJ2)
	$(CC) $(CFLAGS) -o 10.2a $(OBJ2)

10.3: $(OBJ3)
	$(CC) $(CFLAGS) -o 10.3 $(OBJ3)

	
10.1.o: 10.1.cpp

10.2a.o: 10.2a.cpp

10.3.o: 10.3.cpp



clean:
	rm -f 10.1 10.2a 10.3 *.o